# prefix
set -g prefix C-s
unbind C-b

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# name new window 
bind c command-prompt -p "What are we calling it?" "new-window -n '%%'"

# splits
bind | split-window -h
bind - split-window -v

# mouse
set -g mouse on

# start windows at 1
set -g base-index 1

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'barlevalon/tmux-nowplaying'

# dracula
set -g @dracula-plugins "custom:nowplaying.sh custom:battery_icon.sh time"
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "🫠"
set -g @dracula-custom-plugin-colors "pink white"
set -g window-status-current-format "#[bg=#b4637a,fg=#f8f8f2,bold] #I #W #[default]"
# nowplaying
set -g @nowplaying_paused_icon "⏸️ "
set -g @nowplaying_scrolling_enabled "yes"

set -g @dracula-time-format "%a %b %d 🏀 %I:%M %p"

set -g @dracula-colors "
pink='#b4637a'
orange='#d7827e'
yellow='#ea9d34'
green='#879a39'
cyan='#56949f'
purple='#907aa9'
"

# Initialize TPM (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'

